### ISSUE TITLE
Maker offer configuration

### ISSUE THREAD

**Issue by da-kami** [get10101/itchysats#3]
Instead of a static offer the maker has UI fields to create an offer.

**Comment by bonomat** [comment]
What do you think of having _dynamically priced_ offers? 

The user enters a spread instead of a fixed rate for the offer (in addition to other parameters as amounts and leverage). The actual rate is then computed dynamically and periodically using some price feed (e.g. bitmex). 
Whenever the price changes, the maker tells its connected peers that the price has changed.

**Comment by thomaseizinger** [comment]
> What do you think of having _dynamically priced_ offers?
> 
> The user enters a spread instead of a fixed rate for the offer (in addition to other parameters as amounts and leverage). The actual rate is then computed dynamically and periodically using some price feed (e.g. bitmex).
> Whenever the price changes, the maker tells its connected peers that the price has changed.

If I remember correctly, our initial scope was to manually create an offer when we know that someone wants to try out the product with us.

It is a good idea but sounds out of scope from what we have discussed.

**Comment by bonomat** [comment]
Do you think this would change the scope too much?

If so, we could do the same thing without auto update. The interesting part here is that the user (the maker) does not have to do the math to come up with a price but it gets computed automatically.

**Comment by thomaseizinger** [comment]
If we want to keep our existing architecture of dumb frontend with all calculations in the backend then yes it is quite a bit of a change because either

a) you send and store the user's parameters (spread, etc) in the backend so you can compute the price and send it out on the feed / to the takers
b) you provide a calculation endpoint that is hit every time you change any of the inputs

I don't think any of the above are worth doing if all we get out of it is not having the user do some math. We can easily implement this as a feature on top once everything else works.

**Comment by thomaseizinger** [comment]
At the very least, we need the manual thing working first.

I think this actually already implemented anyway and just this ticket is stale.

@da-kami please confirm and close if so.

**Comment by da-kami** [comment]
I propose https://github.com/comit-network/hermes/issues/108

What is described by @bonomat is out of scope for this ticket (will close this ticket).
Please refer to #108 - I think this can be in scope for the MVP. I see automated offer re-publication as out of scope for the MVP.
