### ISSUE TITLE
Provide feedback in the frontend after agreeing on collaborative settlement

### ISSUE THREAD

**Issue by klochowicz** [get10101/itchysats#309]
After agreeing on a collaborative settlement we should change the Cfd state visible to the user (and disable the approve/ reject settlement actions in the maker). 

After the transaction gets published, the Cfd correctly moves to 'closed', but before that user can get pretty confused.

**Comment by da-kami** [comment]
Note: It would be great if both the `maker` and the `taker` would see the status change in the UI - at the moment both remain in `Open` after the maker accepts the proposal. 
I think we can also show something different on the taker side, because the `taker` gets informed that the `maker` accepted the proposal.
