### ISSUE TITLE
Enable the taker to publish the collaborative settlement tx

### ISSUE THREAD

**Issue by da-kami** [get10101/itchysats#320]
We had several discussion about that one in the past, just had another one with @klochowicz  :)

Here is our reasoning why it is more resilient if the maker answers with the signed transaction instead of just telling the taker "accepted, I'll publish it for you..." (which is what we currently do):

The time-component for knowing that it will work out is shorter and less complex if the taker is enabled to publish the transaction as well. 
Currently we have to monitor and then eventually decide to publish commit if we don't see the transactions. 

If the taker's collaborative settlement proposal is answered by the maker with sending the sigend transaction back (and they both try to broadcast) the taker has immediate assurance after the response. Meaning, if the maker does not respond within x time the taker does not have to monitor anything, the taker just publishes commit. 
If the maker responds the taker can ensure that the tx goes in (actually both have to ensure because both have it). That's the same reasoning as for the contract setup. 

## Annoyance counter

- 23/03/2022: The protocol being asymmetric caused https://github.com/itchysats/itchysats/issues/1668 because we don't have a timeout on executing the protocol.
- 24/03/2022: The above problem appeared in production.
- 26/03/2022: The timeout introduced in #1671 appears to be to short which caused a scenarios where the maker timed out while waiting for the `Initiate` message, causing yet another instance of the maker force closing a position while the taker thinks it is being collaboratively settled. 
- 05/04/2022: While working on https://github.com/itchysats/itchysats/pull/1765, @da-kami noticed that without changing this protocol, we cannot republish the collab. settlement transaction.

**Comment by da-kami** [comment]
As part of this ticket we will have to adapt the `monitor` to try re-broadcasting the settlement transaction upon startup. Currently that is not done, which can result in the transaction not being re-broadcasted in case an initial broadcast fails and we restart.

Currently we cannot just re-broadcast the settlement transaction, because the taker's transaction is not fully signed (which should be fixed by this ticket).

**Comment by thomaseizinger** [comment]
As part of looking into https://github.com/itchysats/itchysats/issues/1595, I've thought about how to re-design this protocol. Here are my findings:

1. Collaborative close is _not_ a [2-generals problem](https://en.wikipedia.org/wiki/Two_Generals%27_Problem) because even with the protocol failing on one end, the other party can still proceed.
2. In general, sending messages concurrently (like we do in rollover and contract setup) is a problem. If there is a defined sequence of sending and receiving, receiving a message on A is an implicit ACK from B that the last message was received.

I propose the following design:

```mermaid
sequenceDiagram
	Dialer->>Listener: Open `/itchysats/close-position` protocol
	Dialer->>Listener: Send CfdId and price
	Listener->>Listener: Check if price is favourable
	Listener->>Dialer: Accept
	Dialer->>Dialer: Compute settlement transaction
	Listener->>Listener: Compute settlement transaction
	Dialer->>Listener: Send signature
	Listener->>Dialer: Send signature
```

Although we don't have a strict two-generals problem at hand here, literature still tells us that it is impossible for both parties to be certain that they other party completed the protocol without failure. Assuming a sequential protocol, receiving the listener's signature is an implicit ACK for receiving the dialer's.

The tricky failure case is where the dialer sends their signature but times out on receiving the listener's signature. For this case, we need to assume that the transaction can be published by the listener.

In any case, if the dialer succeeds, it knows that the listener succeeds as well. In case the dailer fails on receiving the listener's signature. We can start to monitor but also retry the protocol. Assuming the same price is sent, the listener implementation SHOULD attempt to be idempotent and use the same addresses during the protocol such that the same signature can be used.

Note that I purposely used the terminology of dialer and listener here. These refer to the role on a substream level and we can decide whether or not only one or both parties support this protocol in listening mode.

**Comment by thomaseizinger** [comment]
> Assuming the same price is sent, the listener implementation SHOULD attempt to be idempotent and use the same addresses during the protocol such that the same signature can be used.

This is a bit tricky to implement at the moment because the decision logic on when to accept the closing of a position is outside of the maker daemon.

There hasn't been much movement on https://github.com/itchysats/architecture/pull/25 and without a decision there, we can't go down that route.

Hence, as a first step, we can implement this protocol without the idempotency part. The consequence of this is that the dialer can finish the protocol in two ways:

- Completely successfully: Signature has been sent and received
- Partially successfully: Signature has been sent but not received

In the latter case, we should not completely fail the protocol but succeed "partially" in the sense that we hope that the listening side will broadcast the transaction for us as they are the only ones that have both signatures at that point. We will likely need an extra event for this case to differentiate, that the transaction we are holding is incomplete.

**Comment by thomaseizinger** [comment]
Ideally, we would implement this protocol as a standalone crate that only depends in `xtra-libp2p` and `model`. Unfortunately, the current protocol code is completely entangled with infrastructure like the DB and the connection actor so this is not possible.

For the taker, we can simply replace the `collab_settlement_taker::Actor` with something new. Once a taker upgrades, there is no need to support the old protocol.
For the maker, we need to retain the old and the new implementation to not break compatibility with older versions.

Ideally, we would use the capability of a multiplexed connection to model the entire protocol as a single future that can simply be run by the executor. I am not sure if this is easily possible in one sweep. Further refactoring may be required before we can go there. The main thing that is awkward here is that the we need to interact with the `Cfd` model 3 times throughout the protocol.

If we manage to transfer all the state into a single task, we could do away with the `collab_settlement_taker::Actor` being ephemeral and simply have it handle all settlements concurrently by means of spawning the individual instances as tasks into the runtime.

**Comment by thomaseizinger** [comment]
> The main thing that is awkward here is that the we need to interact with the `Cfd` model 3 times throughout the protocol.

By making the protocol symmetric (which is the goal of this issue), we can perhaps remove this weirdness by already returning the required signature as part of:
- creating the `SettlementProposal` on the taker side
- receiving the `SettlementProposal` on the maker side

This should allow us to model the protocol as 3 steps:

1. Retrieve `Cfd` from DB, create/receive proposal. Compute all necessary data
2. Spawn away task for sending / receiving messages in order specified by protocol
3. Send result of protocol back to actor, interact with DB again to save result

**Comment by thomaseizinger** [comment]
## Decisions that we still need to make for this new protocol:

- What should the wire encoding be? Do we implement a `Codec` that is basically self-describing or do we just assume the order and types of messages?
	- I think we will need to use a codec. As part of the protocol, we will need to read at least one `enum` from the wire: The maker's decision on whether to accept or reject the closing. This enum is essentially "dynamically-sized", i.e. we don't know ahead of time, how many bytes we need to read so we need some form of meta-data to deserialize this into an enum and that is what a codec will do.
- ... (To be extended as I am prototyping)

**Comment by thomaseizinger** [comment]
## Unsolved problems:

- Establishing a new substream requires knowledge of the `PeerId` to the other party. We currently don't store this in the `Cfd` (we only store the old `maker_id`). Thus, to implement this cleanly, we need to also save the `maker`'s `PeerId` after we create a new CFD before we can close them using this new protocol. Alternatively, we could just assume that the currently connected maker is the correct one but that is very hacky.

**Comment by thomaseizinger** [comment]
Draft work is happening here: https://github.com/itchysats/itchysats/pull/1919

**Comment by klochowicz** [comment]
> ## Unsolved problems:
> * Establishing a new substream requires knowledge of the `PeerId` to the other party. We currently don't store this in the `Cfd` (we only store the old `maker_id`). Thus, to implement this cleanly, we need to also save the `maker`'s `PeerId` after we create a new CFD before we can close them using this new protocol. Alternatively, we could just assume that the currently connected maker is the correct one but that is very hacky.

maybe we could have a single map maker_id -> PeerId whenever we connect to a new maker?

**Comment by thomaseizinger** [comment]
> > ## Unsolved problems:
> > * Establishing a new substream requires knowledge of the `PeerId` to the other party. We currently don't store this in the `Cfd` (we only store the old `maker_id`). Thus, to implement this cleanly, we need to also save the `maker`'s `PeerId` after we create a new CFD before we can close them using this new protocol. Alternatively, we could just assume that the currently connected maker is the correct one but that is very hacky.
> 
> maybe we could have a single map maker_id -> PeerId whenever we connect to a new maker? 

Yes, I too think that that is the best solution. The PeerId field in the DB would be optional and if it is absent, we try to default it based on the maker_id.
